version: "3.8"

services:
  streamlit:
    build: ./backend
    image: realestate-streamlit:local
    ports:
      - "8501:8501"
    volumes:
      - ./:/app  # ローカルコードを反映
    environment:
      - PORT=8501
